<?php
// Code mean: [model][function][type][no.][status] => AABBCCDDE

define('COMMON_CAPTCHA_ERROR',			'010101010');
$GLOBALS['MESSAGE'][COMMON_CAPTCHA_ERROR] = '您输入的字符与显示的不相符，请重试。';
define('COMMON_AGREE_TERMSOFSERVICE',	'010101020');
$GLOBALS['MESSAGE'][COMMON_AGREE_TERMSOFSERVICE] = '要使用我们的服务，您必须同意接受服务条款。';
define('COMMON_ACCOUNTEMPTY',			'010101030');
$GLOBALS['MESSAGE'][COMMON_ACCOUNTEMPTY] = '请输入您的账号。';
define('COMMON_PASSWORDEMPTY',			'010101040');
$GLOBALS['MESSAGE'][COMMON_PASSWORDEMPTY] = '请输入您的密码。';
define('COMMON_NOLOGIN',				'010102010');
$GLOBALS['MESSAGE'][COMMON_NOLOGIN] = '您没有登陆。';
define('COMMON_NOPOWER',				'010102020');
$GLOBALS['MESSAGE'][COMMON_NOPOWER] = '您没有权限。';
define('COMMON_SYSTEMERROR',			'010103010');
$GLOBALS['MESSAGE'][COMMON_SYSTEMERROR] = '系统发生错误，请联系管理员。';
