<?php
// Code mean: model function status num => AABBCDD

// Login
define('MEMBER_LOGIN_UNACTIVE',		'0101001');
$GLOBALS['MESSAGE'][MEMBER_LOGIN_UNACTIVE] = '账号还未激活。';
define('MEMBER_LOGIN_DISABEL',		'0101002');
$GLOBALS['MESSAGE'][MEMBER_LOGIN_DISABEL] = '账号已被禁用。';
define('MEMBER_LOGIN_DELETE',		'0101003');
$GLOBALS['MESSAGE'][MEMBER_LOGIN_DELETE] = '账号已被删除。';
define('MEMBER_LOGIN_UNKNOWSTATUS',	'0101004');
$GLOBALS['MESSAGE'][MEMBER_LOGIN_UNKNOWSTATUS] = '账号状态错误，请联系管理员。';
define('MEMBER_LOGIN_NOTEXIST',		'0101005');
$GLOBALS['MESSAGE'][MEMBER_LOGIN_NOTEXIST] = '账号或密码错误。';
